---

- name: create .env file
  copy:
    src: "{{ git_destination }}/.env.example"
    dest: "{{ git_destination }}/.env"
    force: no
  register: create_env

- name: generate application key
  command: php artisan key:generate
  args:
    chdir: "{{ git_destination }}"
  when: create_env.changed

- name: make laravel directories writable
  file:
    path: "{{ item }}"
    mode: 0777
  with_items:
    - "{{ git_destination }}/bootstrap/cache"
    - "{{ git_destination }}/storage/framework/cache"
    - "{{ git_destination }}/storage/framework/sessions"
    - "{{ git_destination }}/storage/framework/views"
    - "{{ git_destination }}/storage/logs"