---

- name: generate application key
  command: php artisan key:generate
  args:
    chdir: "{{ git_destination }}"

- name: make laravel directories writable
  file:
    path: "{{ item }}"
    mode: 0777
  with_items:
    - "{{ logs_directory }}"
