---

- name: create .env
  copy:
    src: "{{ git_destination }}/.env.example"
    dest: "{{ git_destination }}/.env"
    force: no
  register: create_env

- name: edit .env
  lineinfile:
    dest: "{{ git_destination }}/.env"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^DB_DATABASE=", line: "DB_DATABASE={{ project_name }}" }
    - { regexp: "^DB_USERNAME=", line: "DB_USERNAME=root" }
    - { regexp: "^DB_PASSWORD=", line: "DB_PASSWORD=" }

- name: generate key
  command: php artisan key:generate
  args:
    chdir: "{{ git_destination }}"
  when: create_env.changed

- name: make writable
  file:
    path: "{{ item }}"
    mode: 0777
  failed_when: false
  with_items:
    - "{{ git_destination }}/bootstrap/cache"
    - "{{ git_destination }}/storage/framework/cache"
    - "{{ git_destination }}/storage/framework/sessions"
    - "{{ git_destination }}/storage/framework/views"
    - "{{ git_destination }}/storage/logs"