---

- name: Add hostname to system
  lineinfile:
    dest: "{{ hostfile }}"
    line: "{{ hostip }}\t{{ hostname }}"
  become: yes
  become_user: root

- name: Create virtualhost file
  template:
    src: "{{ virtualhost_source }}"
    dest: "{{ virtualhost_destination }}"
  become: yes
  become_user: root

- name: Enable virtualhost file
  command: a2ensite {{ hostname }}
  become: yes
  become_user: root

# - name: Configure apache2 user and group
#   lineinfile: dest=/etc/apache2/envvars regexp="^export {{ item.param }}=" line="export {{ item.param }}={{ item.value }}"
#   with_items :
#     - { param: APACHE_RUN_USER, value: "{{ apache2.run_as }}" }
#     - { param: APACHE_RUN_GROUP, value: "{{ apache2.run_as }}" }

- name: Restart apache2
  service:
    name: apache2
    state: restarted
    enabled: yes
  become: yes
  become_user: root
