---

- name: Install apache2
  apt:
    name: apache2
  become: yes
  become_user: root

- name: Set servername
  lineinfile:
    dest: "/etc/apache2/apache2.conf"
    line: "ServerName localhost"
  become: yes
  become_user: root

- name: Enable rewrite module
  apache2_module:
    name: rewrite
    state: present
  become: yes
  become_user: root
