---

- hosts: all

  tasks: 
    - name: Get composer.json file info
      stat: 
        path: "{{ ansible_env.PWD }}/composer.json"
      register: composer_status

  roles:
    - git
    - {
      role: "php",
      when: composer_status.stat.exists
    }