---

# ansible-pull -U https://github.com/simondubois/project-installer.git -d . -e "git_repository=https://github.com/simondubois/budget.git" all.yml

- hosts: all
  roles:
    - git
    - analyzer
    - {
      role: php,
      when: "{{ with_composer }}"
    }
