---

# ansible-pull -U https://github.com/simondubois/project-installer.git -d . -e "git_repository=https://github.com/simondubois/budget.git" all.yml

- hosts: all

  pre_tasks: 
    - name: Get composer.json file info
      stat: 
        path: "{{ ansible_env.PWD }}/composer.json"
      register: composer_file
    - set_fact:
        composer_exists: "{{ composer_file.stat.exists }}"
    - debug: msg="{{ composer_file }}"

  roles:
    - git
    - {
      role: php,
      when: "{{ composer_exists }}"
    }
