---

# ansible-pull -U https://github.com/simondubois/project-installer.git -d . -e "git_repository=https://github.com/simondubois/budget.git" all.yml

- hosts: localhost
  roles:
    - git
    - analyzer
    - {
      role: php,
      when: "{{ with_php }}"
    }
    - {
      role: composer,
      when: "{{ with_composer }}"
    }
    - {
      role: apache,
      when: "{{ with_apache }}"
    }
