---

- hosts: all

  tasks: 
    - name: Get composer.json file info
      stat: 
        path: "{{ ansible_env.PWD }}/composer.json"
      register: composer_status
    - set_fact: composer_exists={{ composer_status.stat.exists }}

  roles:
    - git
    - {
      role: php,
      when: composer_exists
    }