---

# ansible-pull -U https://github.com/simondubois/project-installer.git -e "git_repository=https://github.com/simondubois/budget.git git_destination=$PWD"

- hosts: localhost
  roles:
    - git
    - analyzer
    - {
      role: php,
      when: "{{ with_php }}"
    }
    - {
      role: composer,
      when: "{{ with_composer }}"
    }
    - {
      role: laravel,
      when: "{{ with_laravel }}"
    }
    - {
      role: apache,
      when: "{{ with_apache }}"
    }
    - {
      role: mysql,
      when: "{{ with_mysql }}"
    }
    - {
      role: phpmyadmin,
      when: "{{ with_mysql }}"
    }
    - {
      role: apache,
      hostname: "phpmyadmin.dev",
      when: "{{ with_mysql }}"
    }
