---

# ansible-pull -U https://github.com/simondubois/project-installer.git -e "git_repository=https://github.com/simondubois/budget.git git_destination=$PWD"
# ansible-pull -U https://github.com/simondubois/project-installer.git -e "git_repository=https://github.com/simondubois/photos.git git_destination=$PWD"
# ansible-pull -U https://github.com/simondubois/project-installer.git -e "git_repository=https://github.com/simondubois/ubuntu-installer.git git_destination=$PWD"
# ansible-pull -U https://github.com/simondubois/project-installer.git -e "git_repository=https://github.com/simondubois/project-installer.git git_destination=$PWD"
# ansible-pull -U https://github.com/simondubois/project-installer.git -e "git_repository=https://github.com/simondubois/simon.git git_destination=$PWD"

- hosts: localhost
  roles:
    - git
    - analyzer
    - {
      role: php,
      when: "{{ with_php }}"
    }
    - {
      role: composer,
      when: "{{ with_composer }}"
    }
    - {
      role: laravel,
      when: "{{ with_laravel }}"
    }
    - {
      role: lumen,
      when: "{{ with_lumen }}"
    }
    - {
      role: apache,
      hostname: "{{ project_name }}.dev",
      public_path: "{{ public_path }}",
      when: "{{ with_apache }}"
    }
    - {
      role: mysql,
      when: "{{ with_mysql }}"
    }
    - {
      role: phpmyadmin,
      when: "{{ with_mysql }}"
    }
    - {
      role: nodejs,
      when: "{{ with_nodejs }}"
    }
