---

# ansible-pull -U https://github.com/simondubois/project-installer.git -e "git_repository=https://github.com/simondubois/budget.git git_destination=$HOME/dev/budget"
# ansible-pull -U https://github.com/simondubois/project-installer.git -e "git_repository=https://github.com/simondubois/photos.git git_destination=$HOME/dev/photos"
# ansible-pull -U https://github.com/simondubois/project-installer.git -e "git_repository=https://github.com/simondubois/ubuntu-installer.git git_destination=$HOME/dev/ubuntu-installer"
# ansible-pull -U https://github.com/simondubois/project-installer.git -e "git_repository=https://github.com/simondubois/project-installer.git git_destination=$HOME/dev/project-installer"
# ansible-pull -U https://github.com/simondubois/project-installer.git -e "git_repository=https://github.com/simondubois/simon.git git_destination=$HOME/dev/simon"
# ansible-pull -U https://github.com/simondubois/project-installer.git -e "git_repository=https://github.com/simondubois/unsplash-downloader.git git_destination=$HOME/dev/unsplash-downloader"
# ansible-pull -U https://github.com/simondubois/project-installer.git -e "git_repository=https://github.com/simondubois/jsonresume-theme-paper.git git_destination=$HOME/dev/jsonresume-theme-paper"
# ansible-pull -U https://github.com/simondubois/project-installer.git -e "git_repository=https://github.com/simondubois/c4media-test.git git_destination=$HOME/dev/c4media-test"

- hosts: localhost
  roles:
    - git
    - analyzer
    - {
      role: php,
      when: "{{ with_php }}"
    }
    - {
      role: laravel,
      when: "{{ with_laravel }}"
    }
    - {
      role: lumen,
      when: "{{ with_lumen }}"
    }
    - {
      role: composer,
      when: "{{ with_composer }}"
    }
    - {
      role: apache,
      hostname: "{{ project_name }}.dev",
      document_root: "{{ public_path }}",
      when: "{{ with_apache }}"
    }
    - {
      role: mysql,
      when: "{{ with_mysql }}"
    }
    - {
      role: phpmyadmin,
      when: "{{ with_mysql }}"
    }
    - {
      role: nodejs,
      when: "{{ with_nodejs }}"
    }
