---

- name: composer.json file
  stat:
    path: "{{ git_destination }}/composer.json"
  register: composer_file

- name: laravel in composer.json
  command: grep -q '"laravel/framework":' "{{ git_destination }}/composer.json"
  ignore_errors: true
  changed_when: false
  failed_when: false
  register: laravel_required
  when: composer_file.stat.exists

- name: lumen in composer.json
  command: grep -q '"laravel/lumen-framework":' "{{ git_destination }}/composer.json"
  ignore_errors: true
  changed_when: false
  failed_when: false
  register: lumen_required
  when: composer_file.stat.exists

- name: public folder
  stat:
    path: "{{ git_destination }}/public"
  register: public_folder

- name: sql files
  find:
    paths: "{{ git_destination }}"
    patterns: "*.sql"
  register: sql_files

- name: migration files
  find:
    paths: "{{ git_destination }}/database/migrations"
    patterns: "*.php"
  register: migration_files
  when: laravel_required.rc == 0 or lumen_required.rc == 0

- name: seeds files
  find:
    paths: "{{ git_destination }}/database/seeds"
    patterns: "*.php"
  register: seed_files
  when: laravel_required.rc == 0 or lumen_required.rc == 0

- name: package.json file
  stat:
    path: "{{ git_destination }}/package.json"
  register: package_file

- name: set facts
  set_fact:
    with_php: "{{ composer_file.stat.exists }}"
    with_composer: "{{ composer_file.stat.exists }}"
    with_apache: "{{ public_folder.stat.exists and public_folder.stat.isdir }}"
    with_laravel: "{{ laravel_required.rc == 0 or lumen_required.rc == 0 }}"
    with_mysql: "{{ sql_files.matched > 0 or (migration_files|success and migration_files.matched > 2) or (seed_files|success and seed_files.matched > 1) }}"
    with_nodejs: "{{ package_file.stat.exists }}"
    project_name: "{{ git_repository | basename | regex_replace('.git$', '') }}"
