---

- name: Detect composer.json file
  stat:
    path: "{{ git_destination }}/composer.json"
  register: composer_file

- name: Detect laravel in composer.json
  command: grep -q '"laravel/framework":' "{{ git_destination }}/composer.json"
  ignore_errors: true
  changed_when: false
  register: laravel_required
  when: composer_file.stat.exists

- name: Detect public folder
  stat:
    path: "{{ git_destination }}/public"
  register: public_folder

- name: Detect sql files
  find:
    paths: "{{ git_destination }}"
    patterns: "*.sql"
  register: sql_files

- name: Detect migration files
  find:
    paths: "{{ git_destination }}/database/migrations"
    patterns: "*.php"
  when: laravel_required.rc == 0
  register: migration_files

- name: Detect seeds files
  find:
    paths: "{{ git_destination }}/database/seeds"
    patterns: "*.php"
  when: laravel_required.rc == 0
  register: seed_files

- name: Set analyze results
  set_fact:
    with_php: "{{ composer_file.stat.exists }}"
    with_composer: "{{ composer_file.stat.exists }}"
    with_apache: "{{ public_folder.stat.exists and public_folder.stat.isdir }}"
    with_laravel: "{{ laravel_required.rc == 0 }}"
    with_mysql: "{{ sql_files.matched > 0 or migration_files.matched > 2 or seed_files.matched > 1 }}"
    public_path: "{{ public_folder.stat.path }}"
    project_name: "{{ git_repository | basename | regex_replace('.git$', '') }}"
    hostname: "{{ git_repository | basename | regex_replace('.git$', '') }}.dev"
