---

- name: composer.json file
  stat:
    path: "{{ git_destination }}/composer.json"
  register: composer_file

- name: laravel in composer.json
  command: grep -q '"laravel/framework":' "{{ git_destination }}/composer.json"
  ignore_errors: true
  changed_when: false
  failed_when: false
  register: laravel_required
  when: composer_file.stat.exists

- name: lumen in composer.json
  command: grep -q '"laravel/lumen-framework":' "{{ git_destination }}/composer.json"
  ignore_errors: true
  changed_when: false
  failed_when: false
  register: lumen_required
  when: composer_file.stat.exists

- name: index file / public folder
  set_fact:
    public_path: "{{ item }}"
  with_first_found:
    - "{{ git_destination }}/index.php"
    - "{{ git_destination }}/index.html"
    - "{{ git_destination }}/public/index.php"
    - "{{ git_destination }}/public/index.html"

- debug:
    msg: "{{ public_path }}"

- name: sql files
  find:
    paths: "{{ git_destination }}"
    patterns: "*.sql"
  register: sql_files

- name: migration files
  find:
    paths: "{{ git_destination }}/database/migrations"
    patterns: "*.php"
  register: migration_files

- name: seeds files
  find:
    paths: "{{ git_destination }}/database/seeds"
    patterns: "*.php"
  register: seed_files

- name: package.json file
  stat:
    path: "{{ git_destination }}/package.json"
  register: package_file

- name: set facts
  set_fact:
    with_php: "{{ composer_file.stat.exists }}"
    with_composer: "{{ composer_file.stat.exists }}"
    with_apache: "{{ public_path }}"
    with_laravel: "{{ composer_file.stat.exists and laravel_required.rc == 0 }}"
    with_lumen: "{{ composer_file.stat.exists and lumen_required.rc == 0 }}"
    with_mysql: "{{ sql_files.matched > 0 or (migration_files|success and migration_files.matched > 2) or (seed_files|success and seed_files.matched > 1) }}"
    with_nodejs: "{{ package_file.stat.exists }}"
    project_name: "{{ git_repository | basename | regex_replace('.git$', '') }}"
