---

- name: create .env
  copy:
    src: "{{ git_destination }}/.env.example"
    dest: "{{ git_destination }}/.env"
    force: no
  register: create_env

- name: edit .env
  lineinfile:
    dest: "{{ git_destination }}/.env"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^DB_DATABASE=", line: "DB_DATABASE={{ project_name }}" }
    - { regexp: "^DB_USERNAME=", line: "DB_USERNAME=root" }
    - { regexp: "^DB_PASSWORD=", line: "DB_PASSWORD=" }
  when: "{{ with_mysql }}"

- name: generate key
  command: php -r "echo md5(uniqid());"
  register: generate_key
  when: create_env.changed

- name: save key
  lineinfile:
    dest: "{{ git_destination }}/.env"
    regexp: "^APP_KEY="
    line: "APP_KEY={{ generate_key.output }}"
  when: create_env.changed

- name: make writable
  file:
    path: "{{ item }}"
    mode: 0777
  with_items:
    - "{{ git_destination }}/storage/framework/cache"
    - "{{ git_destination }}/storage/framework/sessions"
    - "{{ git_destination }}/storage/framework/views"
    - "{{ git_destination }}/storage/logs"