---

# - name: Installing apt-key
#   apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

# - name: Import the NodeSource GPG key into apt
#   apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  become: yes
  become_user: root

- name: repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_5.x {{ ansible_distribution_release }} main"
  become: yes
  become_user: root

- name: install
  apt:
    name: nodejs
  become: yes
  become_user: root

- name: npm install
  apt:
    name: npm
  become: yes
  become_user: root
