---

# - name: Installing apt-key
#   apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

# - name: Import the NodeSource GPG key into apt
#   apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_5.x {{ ansible_distribution_release }} main'

- name: install
  apt:
    name: nodejs
