---

- name: add key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  become: yes
  become_user: root

- name: add repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_5.x {{ ansible_distribution_release }} main"
  become: yes
  become_user: root

- name: install package
  apt:
    name: nodejs
  become: yes
  become_user: root

- name: install dependencies
  command: npm install
  args:
    chdir: "{{ git_destination }}"
