---

- name: install
  apt:
    name: "phpmyadmin"
  become: yes
  become_user: root

- name: enable
  file:
    src: "/usr/share/phpmyadmin"
    dest: "/var/www/html/phpmyadmin"
    state: link
  become: yes
  become_user: root
