---

- name: add repository
  apt_repository:
    repo: "ppa:nijel/phpmyadmin"
  become: yes
  become_user: root

- name: add repository
  apt_repository:
    repo: "ppa:ondrej/php"
  become: yes
  become_user: root

- name: install
  apt:
    name: "phpmyadmin"
  become: yes
  become_user: root

- name: configure
  copy:
    src: "custom.config.inc.php"
    dest: "/etc/phpmyadmin/conf.d/custom.config.inc.php"
  become: yes
  become_user: root
