---

- name: install mysql
  apt:
    pkg: "{{ item }}"
  with_items:
    - mysql-client-5.5
    - mysql-server-5.5
    - python-mysqldb
  become: yes
  become_user: root

- name: install php driver
  apt:
    pkg: php5-mysql
  when: "{{ with_php }}"
  become: yes
  become_user: root

# - name: start mysql
#   service:
#     name: mysql
#     state: started
#   become: yes
#   become_user: root

# - name: set mysql credentials
#   mysql_user:
#     name: "{{ user }}"
#     password: "{{ password }}"

# - name: Remove the MySQL test database
#   mysql_db: db=test state=absent login_user=root login_password={{ mysql.password }}

- name: restart mysql
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes
  become_user: root
