---

- name: install mysql
  apt:
    name: "{{ item }}"
  with_items:
    - mysql-client-5.5
    - mysql-server-5.5
    - python-mysqldb
  become: yes
  become_user: root

- name: restart
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes
  become_user: root
