---

- name: install package
  apt:
    name: "{{ item }}"
  with_items:
    - mysql-client-5.5
    - mysql-server-5.5
    - python-mysqldb
  become: yes
  become_user: root

- name: copy configuration
  copy:
    src: ".my.cnf"
    dest: "{{ ansible_env.HOME }}/.my.cnf"

- name: start service
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes
  become_user: root
