---

- name: create directory
  file:
    path: "{{ git_destination }}"
    state: directory

- name: clone repository
  git:
    repo: "{{ git_repository }}"
    dest: "{{ git_destination }}"
    version: "{{ (git_version is defined) | ternary(git_version,'HEAD') }}"
    accept_hostkey: true
