---

- name: add repository
  apt_repository:
    repo: "ppa:ondrej/php"
  become: yes
  become_user: root

- name: install package
  apt:
    name: php5
  become: yes
  become_user: root

- name: enable php5
  file:
    src: "/usr/bin/php5"
    dest: "/etc/alternatives/php"
    state: link

- name: mysql driver
  apt:
    name: php5-mysqlnd
  become: yes
  become_user: root
  when: "{{ with_mysql }}"

- name: install curl
  apt:
    name: php5-curl
  become: yes
  become_user: root

- name: install mcrypt
  apt:
    name: php5-mcrypt
  become: yes
  become_user: root
  register: install_mcrypt

- name: enable mcrypt
  command: php5enmod mcrypt
  when: not install_mcrypt|skipped and install_mcrypt|changed
  become: yes
  become_user: root

- name: install xdebug
  apt:
    name: php5-xdebug
  become: yes
  become_user: root
  register: install_xdebug

- name: configure xdebug
  lineinfile:
    dest: /etc/php5/mods-available/xdebug.ini
    regexp: 'xdebug.max_nesting_level='
    line: 'xdebug.max_nesting_level=500'
  become: yes
  become_user: root

- name: enable xdebug
  command: php5enmod xdebug
  when: not install_xdebug|skipped and install_xdebug|changed
  become: yes
  become_user: root

- name: disable phar.readonly
  lineinfile:
    dest: /etc/php5/cli/php.ini
    regexp: '^(.*)phar.readonly( *)='
    line: 'phar.readonly = Off'
  become: yes
  become_user: root

- name: set session.save_path
  lineinfile:
    dest: /etc/php5/apache2/php.ini
    regexp: '^(;*)session.save_path( *)='
    line: 'session.save_path = "/tmp"'
  become: yes
  become_user: root
