---

- name: Install php5
  apt:
    name: php5
  become: yes
  become_user: root

- name: Install mysql driver
  apt:
    name: php5
  become: yes
  become_user: root
  when: "{{ with_mysql }}"

- name: Install mcrypt
  apt:
    name: php5-mcrypt
  become: yes
  become_user: root

- name: Enable mcrypt
  command: php5enmod mcrypt
  become: yes
  become_user: root
