---

- name: install package
  apt:
    name: php5
  become: yes
  become_user: root

- name: mysql driver
  apt:
    name: php5-mysqlnd
  become: yes
  become_user: root
  when: "{{ with_mysql }}"

- name: install curl
  apt:
    name: php5-curl
  become: yes
  become_user: root

- name: install mcrypt
  apt:
    name: php5-mcrypt
  become: yes
  become_user: root
  register: install_mcrypt

- name: enable mcrypt
  command: php5enmod mcrypt
  when: not install_mcrypt|skipped and install_mcrypt|changed
  become: yes
  become_user: root

- name: disable phar.readonly
  lineinfile:
    dest: /etc/php5/cli/php.ini
    regexp: '^(.*)phar.readonly( *)='
    line: 'phar.readonly = Off'
  become: yes
  become_user: root
