---

- name: install package
  apt:
    name: php5
  become: yes
  become_user: root

- name: mysql driver
  apt:
    name: php5-mysqlnd
  become: yes
  become_user: root
  when: "{{ with_mysql }}"
  register: install_mcrypt

- name: install mcrypt
  apt:
    name: php5-mcrypt
  become: yes
  become_user: root
  when: install_mcrypt.changed

- name: enable mcrypt
  command: php5enmod mcrypt
  become: yes
  become_user: root
